### ISSUE TITLE
Crash when parsing the mail #4000

### ISSUE THREAD

**Issue by keram79** [0xbsec/gmail_analyzer#1]
I just downloaded and attempted to try gmail_analyzer. After overcoming the credentials.json (not documented here) issue, I could successfully start the python app, but it crashed with a message I'm unable to debug.

I'm running on MacOS Catalina 10.15.2 with Python 3.7.4.

```
python3 analyzer.py --top 10                                                                                                  
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=661...
* Fetching messages page 614
* Fetching messages meta data  |██                              | 4000/61410Traceback (most recent call last):
  File "analyzer.py", line 39, in <module>
    Metrics(args).start()
  File "/Users/username/gmail_analyzer/src/metrics.py", line 233, in start
    self.processor.get_metadata(messages)
  File "/Users/username/gmail_analyzer/src/processor.py", line 122, in get_metadata
    batch.execute()
  File "/Users/username/.local/share/virtualenvs/gmail_analyzer-o07J9XyI/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/username/.local/share/virtualenvs/gmail_analyzer-o07J9XyI/lib/python3.7/site-packages/googleapiclient/http.py", line 1493, in execute
    callback(request_id, response, exception)
  File "/Users/username/gmail_analyzer/src/processor.py", line 79, in process_message
    "labels": response["labelIds"],
KeyError: 'labelIds'
```

**Comment by re4388** [comment]
how to overcome credentials.json?

**Comment by DNNhost** [comment]
yes. what is the format of credentials.json ?
