### ISSUE TITLE
Document credentials.json

### ISSUE THREAD

**Issue by matthewmrichter** [0xbsec/gmail_analyzer#14]
I installed this and ran it according to directions. Pip env set to Python 3.10. OS is MacOS Ventura. I'm getting a 'src/credentials.json not found` error.

```
✗ python3 analyzer.py --user <username>@gmail.com
Traceback (most recent call last):
  File "/Users/matthewrichter/Documents/gmail_analyzer/analyzer.py", line 39, in <module>
    Metrics(args).start()
  File "/Users/matthewrichter/Documents/gmail_analyzer/src/metrics.py", line 20, in __init__
    self.processor = Processor()
  File "/Users/matthewrichter/Documents/gmail_analyzer/src/processor.py", line 16, in __init__
    self.service = Service().instance()
  File "/Users/matthewrichter/Documents/gmail_analyzer/src/service.py", line 13, in instance
    service = build("gmail", "v1", credentials=self._get_creds())
  File "/Users/matthewrichter/Documents/gmail_analyzer/src/service.py", line 32, in _get_creds
    flow = InstalledAppFlow.from_client_secrets_file(
  File "/Users/matthewrichter/.local/share/virtualenvs/gmail_analyzer-0bWCUtY6/lib/python3.10/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'src/credentials.json'
```

I don't see any documentation in the repo about credentials.

**Comment by Dweinbach** [comment]
same on Windows.
